name: Kraken2 DB Release

on:
    push:
      branches:
        - main
      tags:
        - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: quay.io/biocontainers/kraken2:2.1.3--pl5321hdcf5f25_1

    strategy:
      matrix:
        include:
          - ACC_ID: GCF_000001405.40
            ACC_NAME: GRCh38.p14
            LIBS: "bacteria,plasmid"
            NAME: human_only
            VERSION: 1.0.0
          - ACC_ID: GCF_000001405.40
            ACC_NAME: GRCh38.p14
            LIBS: ""
            NAME: human_bact
            VERSION: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and compress database
        if: github.event.release.tag_name == "v${{ matrix.VERSION }}"
        run: |
          bash build_custom_db.sh -i ${{ matrix.ACC_ID }} -n ${{ matrix.ACC_NAME }} -l "${{ matrix.LIBS }}" -o $${{ matrix.NAME }} -t 4
          tar xvzf ${{ matrix.NAME }}

      - name: Release database
        if: github.event.release.tag_name == "v${{ matrix.VERSION }}"
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.NAME }}.tar.gz"
          path: "${{ matrix.NAME }}.tar.gz"

      - name: Create release
        if: github.event.release.tag_name == "v${{ matrix.VERSION }}"
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ matrix.VERSION }}"
          release_name: "${{ matrix.NAME }} v${{ matrix.VERSION }}"
          draft: false
          prerelease: false
          body: "Release of ${{ matrix.NAME }} database version ${{ matrix.VERSION }}"
